"""init_cms_models

Revision ID: 4ef7ac13bffb
Revises: 
Create Date: 2026-06-21 10:03:27.754418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef7ac13bffb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_types_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_types_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_content_types_slug'), ['slug'], unique=True)

    op.create_table('content_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_type_id'], ['content_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_entries_id'), ['id'], unique=False)

    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_unique', sa.Boolean(), nullable=True),
    sa.Column('is_translatable', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.JSON(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_type_id'], ['content_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_type_id', 'name', name='uq_field_content_type_name')
    )
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fields_id'), ['id'], unique=False)

    op.create_table('entry_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('field_values', sa.JSON(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('slug', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['content_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'language_code', name='uq_translation_entry_language')
    )
    with op.batch_alter_table('entry_translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entry_translations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entry_translations_language_code'), ['language_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_entry_translations_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry_translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entry_translations_slug'))
        batch_op.drop_index(batch_op.f('ix_entry_translations_language_code'))
        batch_op.drop_index(batch_op.f('ix_entry_translations_id'))

    op.drop_table('entry_translations')
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fields_id'))

    op.drop_table('fields')
    with op.batch_alter_table('content_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_entries_id'))

    op.drop_table('content_entries')
    with op.batch_alter_table('content_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_types_slug'))
        batch_op.drop_index(batch_op.f('ix_content_types_name'))
        batch_op.drop_index(batch_op.f('ix_content_types_id'))

    op.drop_table('content_types')
    # ### end Alembic commands ###
